// AUTO-GENERATED by scripts/generate-app-paths.mjs - do not edit manually.
// Source: src/playground/routes.tsx (20 paths)

export type AppPaths =
	| '/'
	| '/playground'
	| '/playground/scroll'
	| '/playground/retry'
	| '/playground/retry-raw'
	| '/playground/live'
	| '/playground/actions'
	| '/playground/prefetch'
	| '/playground/optimistic'
	| '/playground/nest'
	| '/playground/nest/:nestId'
	| '/playground/nest/:nestId/item/:itemId'
	| '/playground/cache'
	| '/playground/product/:productId'
	| '/playground/heavy'
	| '/playground/search'
	| '/playground/guard'
	| '/playground/dashboard'
	| '/playground/blocker'
	| '/playground/settings'
	;
